# Generated by Django 5.0.7 on 2024-07-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_participants_alter_expense_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='split_method',
        ),
        migrations.RemoveField(
            model_name='expensesplit',
            name='amount_owed',
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='method',
            field=models.CharField(choices=[('equal', 'Equal'), ('exact', 'Exact'), ('percentage', 'Percentage')], default='equal', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
